fix: update `ttypescript` to fix build error
Previously build failed with:

    /Users/riski/code/work/tsc-output-parser/node_modules/ttypescript/lib/loadTypescript.js:29
    var _e = ts.versionMajorMinor.split('.'), major = _e[0], minor = _e[1];
                                  ^

    TypeError: Cannot read properties of undefined (reading 'split')
        at Object.loadTypeScript (/Users/riski/code/work/tsc-output-parser/node_modules/ttypescript/lib/loadTypescript.js:29:35)
        at Object.<anonymous> (/Users/riski/code/work/tsc-output-parser/node_modules/ttypescript/lib/tsc.js:8:27)
        at Module._compile (node:internal/modules/cjs/loader:1218:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
        at Module.load (node:internal/modules/cjs/loader:1081:32)
        at Module._load (node:internal/modules/cjs/loader:922:12)
        at Module.require (node:internal/modules/cjs/loader:1105:19)
        at require (node:internal/modules/cjs/helpers:103:18)
        at Object.<anonymous> (/Users/riski/code/work/tsc-output-parser/node_modules/ttypescript/bin/tsc:2:1)
        at Module._compile (node:internal/modules/cjs/loader:1218:14)

See https://github.com/cevek/ttypescript/issues/139.